import { Platform } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import { createStyleSheet } from 'react-native-unistyles';

export const modelStyles = createStyleSheet(() => ({
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    shadowOffset: { width: 1, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    shadowColor: '#333333',
    elevation: 5,
    zIndex: 1,
    padding: 10,
  },
  vegIcon: {
    width: 15,
    height: 15,
    top: 3,
    resizeMode: 'contain',
  },
  noShadowHeaderContainer: {
    borderBottomWidth: 1,
    borderColor: '#CCCCCC',
    backgroundColor: '#FFFFFF',
    zIndex: 1,
    padding: 15,
  },
  flexRowGap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  flexRowItemBaseline: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    paddingVertical: 10,
    borderBottomColor: '#CCCCCC',
  },
  flexRowGapBaseline: {
    flexDirection: 'row',
    width: '70%',
    alignItems: 'flex-start',
    gap: 10,
  },
  icon: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowColor: '#333333',
    elevation: 5,
    borderRadius: 100,
  },
  headerImage: {
    width: 40,
    height: 40,
    resizeMode: 'cover',
    borderRadius: 12,
  },
  scrollContainer: {
    backgroundColor: '#F5F5F5',
    padding: 10,
  },
  scrollContainerWhiteBackground: {
    backgroundColor: '#FFFFFF',
    padding: 10,
  },
  subContainer: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 10,
    marginVertical: 10,
  },
  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    shadowOffset: { width: 1, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    shadowColor: '#333333',
    elevation: 5,
    zIndex: 2,
    padding: 10,
    paddingBottom: Platform.OS === 'ios' ? 30 : 10,
  },
  noShadowFooterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    padding: 15,
    paddingBottom: Platform.OS === 'ios' ? 30 : 10,
  },
  selectedContainer: {
    height: 45,
    width: '30%',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#00AA55',
    borderRadius: 12,
    backgroundColor: '#D1F2E0',
  },
  animatedCount: {
    fontSize: RFValue(16),
    color: '#000000',
    fontFamily: 'Okra-Bold',
    margin: 0,
  },
  addButtonContainer: {
    backgroundColor: '#00AA55',
    borderRadius: 10,
    width: '65%',
    justifyContent: 'center',
    alignItems: 'center',
    height: 45,
  },
  selectedOptions: {
    opacity: 0.6,
    marginTop: 2,
  },
  cartOperationContainer: {
    width: '25%',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  miniAddButtonContainer: {
    backgroundColor: '#E0F7F1',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 30,
  },
  miniAnimatedCount: {
    fontSize: RFValue(12),
    color: '#000000',
    fontFamily: 'Okra-Bold',
    marginHorizontal: 12,
    marginLeft: 14,
  },
}));
